name: notification_center
description: A lightweight, easy-to-use notification component library that corresponds to Dart supports post notification listening for notifications and notification removal
version:  1.0.0+1
homepage: https://github.com/netyouli/Flutter-NotificationCenter
author: netyouli <712641411@qq.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true